security:

    encoders:
      Symfony\Component\Security\Core\User\User:
          algorithm: bcrypt
          cost: 12

    providers:
        in_memory:
            memory:
              users:
                ccmunam:
                    password: $2a$04$c8U8C6TIMkMmj3jT2qzeTOYntwHO3hPQKc7XBXGDEPYfil38MNeIG
                    roles: 'ROLE_USER'
                admin:
                    password: $2a$04$4KnXlOcPoy0oBaDoAbQ63.m8P1x5OilA2Syyh2NiQhi4pPJtMNfLq
                    roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
              login_path: /login
              check_path: /login_check
            logout:
              path:   /logout
              target: /login

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cfdi, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_USER }


